version: '3'

services:
  nodejs:
    build: ./nodeApp
    container_name: listplacetakeapp
    restart: unless-stopped
    env_file: ./nodeApp/.env
    environment:
      - MYSQL_HOSTNAME='us-cdbr-iron-east-05.cleardb.net'
      - MYSQL_USERNAME='b92a6b073d3b29'
      - MYSQL_PASSWORD='b91cc937'
      - MYSQL_DB='heroku_3f57e6b34e159e8'
    ports:
      - "8080:8080"
    volumes:
      - ./nodeApp:/usr/src/app